app:
  api-key: ${API_KEY}
cloud:
  aws:
    s3:
      base-url: ${S3_BASE_URL}
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
spring:
  application:
    name: tech-blog

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  file:
    path: /app/logs
  level:
    root: INFO
    org.springframework.security: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always

server:
  port: 8080
  forward-headers-strategy: framework